// <auto-generated>
//     GENERATED FROM @portal/protocol — DO NOT EDIT.
//
//     The protocol's vocabulary, emitted rather than retyped. A review found
//     the Python SDK sending a toast level of "danger" — a component tone the
//     hub refuses — because it had been hand-copied and got one word wrong.
//     Three languages means three chances to make that mistake.
// </auto-generated>
#nullable enable

namespace Portal.Sdk;

/// <summary>Constants the hub defines.</summary>
public static class Protocol
{
    /// <summary>The version this SDK emits.</summary>
    public const string Version = "1.1";

    /// <summary>The components whose schema declares <c>source</c>.</summary>
    public static readonly IReadOnlySet<string> Citable = new HashSet<string>
    {
        "StatTile",
        "KeyValueList",
        "Table",
        "Chart",
    };
}

/// <summary>Toast levels. Note <c>Error</c>, not <c>Danger</c> — that is a component tone.</summary>
public enum ToastLevel
{
    /// <summary>The protocol value <c>success</c>.</summary>
    Success,

    /// <summary>The protocol value <c>info</c>.</summary>
    Info,

    /// <summary>The protocol value <c>warning</c>.</summary>
    Warning,

    /// <summary>The protocol value <c>error</c>.</summary>
    Error,
}

/// <summary>What an action reports back.</summary>
public enum ActionOutcome
{
    /// <summary>The protocol value <c>ok</c>.</summary>
    Ok,

    /// <summary>The protocol value <c>error</c>.</summary>
    Error,

    /// <summary>The protocol value <c>validation</c>.</summary>
    Validation,
}

/// <summary>The type an action parameter carries. Screens take strings only.</summary>
/// <remarks>
/// A screen param arrives in a query string and is therefore always a string.
/// An action payload is JSON, where <c>{"quantity": 2}</c> and
/// <c>{"quantity": "2"}</c> are different values, so an action must say which
/// it expects — and the hub rejects an action parameter that does not.
/// </remarks>
public enum ParamType
{
    /// <summary>The protocol value <c>string</c>.</summary>
    String,

    /// <summary>The protocol value <c>number</c>.</summary>
    Number,

    /// <summary>The protocol value <c>boolean</c>.</summary>
    Boolean,
}

/// <summary>Who a satellite, screen or action is visible to. Default-deny.</summary>
public enum Audience
{
    /// <summary>The protocol value <c>internal</c>.</summary>
    Internal,

    /// <summary>The protocol value <c>external</c>.</summary>
    External,
}

/// <summary>Converts protocol enums to the strings the wire format uses.</summary>
public static partial class WireValues
{
    /// <summary>The protocol string for a <see cref="ToastLevel"/>.</summary>
    public static string ToWire(this ToastLevel value) =>
        value switch
        {
            ToastLevel.Success => "success",
            ToastLevel.Info => "info",
            ToastLevel.Warning => "warning",
            ToastLevel.Error => "error",
            _ => throw new ArgumentOutOfRangeException(nameof(value)),
        };

    /// <summary>The protocol string for an <see cref="ActionOutcome"/>.</summary>
    public static string ToWire(this ActionOutcome value) =>
        value switch
        {
            ActionOutcome.Ok => "ok",
            ActionOutcome.Error => "error",
            ActionOutcome.Validation => "validation",
            _ => throw new ArgumentOutOfRangeException(nameof(value)),
        };

    /// <summary>The protocol string for a <see cref="ParamType"/>.</summary>
    public static string ToWire(this ParamType value) =>
        value switch
        {
            ParamType.String => "string",
            ParamType.Number => "number",
            ParamType.Boolean => "boolean",
            _ => throw new ArgumentOutOfRangeException(nameof(value)),
        };

    /// <summary>The protocol string for an <see cref="Audience"/>.</summary>
    public static string ToWire(this Audience value) =>
        value switch
        {
            Audience.Internal => "internal",
            Audience.External => "external",
            _ => throw new ArgumentOutOfRangeException(nameof(value)),
        };
}
