// <auto-generated>
//     GENERATED FROM THE CATALOG — DO NOT EDIT.
//
//     Run `pnpm sdk:csharp` to regenerate; `pnpm sdk:check` fails if this
//     file is stale. Catalog version 1.0, 34 components.
//
//     Props are named arguments; children go through .With(), because C# will
//     not accept params before optional arguments:
//
//         Ui.Page(title: "Fleet").With(
//             Ui.Grid(columns: 3).With(
//                 Ui.StatTile(label: "Vehicles", value: "12"),
//                 Ui.StatTile(label: "Active", value: "9", tone: Tone.Success)));
//
//     A misspelled prop or a wrong enum value does not compile.
// </auto-generated>
#nullable enable

namespace Portal.Sdk;

/// <summary>Values the catalog accepts for this prop.</summary>
public enum AlertLevel
{
    /// <summary>The catalog value <c>info</c>.</summary>
    Info,

    /// <summary>The catalog value <c>success</c>.</summary>
    Success,

    /// <summary>The catalog value <c>warning</c>.</summary>
    Warning,

    /// <summary>The catalog value <c>error</c>.</summary>
    Error,
}

/// <summary>Converts generated enums to the values the wire format uses.</summary>
public static partial class WireValues
{
    /// <summary>The catalog value for a <see cref="AlertLevel"/>.</summary>
    public static string ToWire(this AlertLevel value) =>
        value switch
        {
            AlertLevel.Info => "info",
            AlertLevel.Success => "success",
            AlertLevel.Warning => "warning",
            AlertLevel.Error => "error",
            _ => throw new ArgumentOutOfRangeException(nameof(value)),
        };
}

/// <summary>Values the catalog accepts for this prop.</summary>
public enum Align
{
    /// <summary>The catalog value <c>start</c>.</summary>
    Start,

    /// <summary>The catalog value <c>center</c>.</summary>
    Center,

    /// <summary>The catalog value <c>end</c>.</summary>
    End,
}

/// <summary>Converts generated enums to the values the wire format uses.</summary>
public static partial class WireValues
{
    /// <summary>The catalog value for a <see cref="Align"/>.</summary>
    public static string ToWire(this Align value) =>
        value switch
        {
            Align.Start => "start",
            Align.Center => "center",
            Align.End => "end",
            _ => throw new ArgumentOutOfRangeException(nameof(value)),
        };
}

/// <summary>Values the catalog accepts for this prop.</summary>
public enum ButtonVariant
{
    /// <summary>The catalog value <c>primary</c>.</summary>
    Primary,

    /// <summary>The catalog value <c>secondary</c>.</summary>
    Secondary,

    /// <summary>The catalog value <c>danger</c>.</summary>
    Danger,

    /// <summary>The catalog value <c>ghost</c>.</summary>
    Ghost,
}

/// <summary>Converts generated enums to the values the wire format uses.</summary>
public static partial class WireValues
{
    /// <summary>The catalog value for a <see cref="ButtonVariant"/>.</summary>
    public static string ToWire(this ButtonVariant value) =>
        value switch
        {
            ButtonVariant.Primary => "primary",
            ButtonVariant.Secondary => "secondary",
            ButtonVariant.Danger => "danger",
            ButtonVariant.Ghost => "ghost",
            _ => throw new ArgumentOutOfRangeException(nameof(value)),
        };
}

/// <summary>Values the catalog accepts for this prop.</summary>
public enum ChartKind
{
    /// <summary>The catalog value <c>line</c>.</summary>
    Line,

    /// <summary>The catalog value <c>bar</c>.</summary>
    Bar,

    /// <summary>The catalog value <c>area</c>.</summary>
    Area,

    /// <summary>The catalog value <c>donut</c>.</summary>
    Donut,
}

/// <summary>Converts generated enums to the values the wire format uses.</summary>
public static partial class WireValues
{
    /// <summary>The catalog value for a <see cref="ChartKind"/>.</summary>
    public static string ToWire(this ChartKind value) =>
        value switch
        {
            ChartKind.Line => "line",
            ChartKind.Bar => "bar",
            ChartKind.Area => "area",
            ChartKind.Donut => "donut",
            _ => throw new ArgumentOutOfRangeException(nameof(value)),
        };
}

/// <summary>Values the catalog accepts for this prop.</summary>
public enum Gap
{
    /// <summary>The catalog value <c>none</c>.</summary>
    None,

    /// <summary>The catalog value <c>xs</c>.</summary>
    Xs,

    /// <summary>The catalog value <c>sm</c>.</summary>
    Sm,

    /// <summary>The catalog value <c>md</c>.</summary>
    Md,

    /// <summary>The catalog value <c>lg</c>.</summary>
    Lg,
}

/// <summary>Converts generated enums to the values the wire format uses.</summary>
public static partial class WireValues
{
    /// <summary>The catalog value for a <see cref="Gap"/>.</summary>
    public static string ToWire(this Gap value) =>
        value switch
        {
            Gap.None => "none",
            Gap.Xs => "xs",
            Gap.Sm => "sm",
            Gap.Md => "md",
            Gap.Lg => "lg",
            _ => throw new ArgumentOutOfRangeException(nameof(value)),
        };
}

/// <summary>Values the catalog accepts for this prop.</summary>
public enum HeadingLevel
{
    /// <summary>The catalog value <c>1</c>.</summary>
    Level1,

    /// <summary>The catalog value <c>2</c>.</summary>
    Level2,

    /// <summary>The catalog value <c>3</c>.</summary>
    Level3,

    /// <summary>The catalog value <c>4</c>.</summary>
    Level4,
}

/// <summary>Converts generated enums to the values the wire format uses.</summary>
public static partial class WireValues
{
    /// <summary>The catalog value for a <see cref="HeadingLevel"/>.</summary>
    public static int ToWire(this HeadingLevel value) =>
        value switch
        {
            HeadingLevel.Level1 => 1,
            HeadingLevel.Level2 => 2,
            HeadingLevel.Level3 => 3,
            HeadingLevel.Level4 => 4,
            _ => throw new ArgumentOutOfRangeException(nameof(value)),
        };
}

/// <summary>Values the catalog accepts for this prop.</summary>
public enum Size
{
    /// <summary>The catalog value <c>sm</c>.</summary>
    Sm,

    /// <summary>The catalog value <c>md</c>.</summary>
    Md,

    /// <summary>The catalog value <c>lg</c>.</summary>
    Lg,
}

/// <summary>Converts generated enums to the values the wire format uses.</summary>
public static partial class WireValues
{
    /// <summary>The catalog value for a <see cref="Size"/>.</summary>
    public static string ToWire(this Size value) =>
        value switch
        {
            Size.Sm => "sm",
            Size.Md => "md",
            Size.Lg => "lg",
            _ => throw new ArgumentOutOfRangeException(nameof(value)),
        };
}

/// <summary>Values the catalog accepts for this prop.</summary>
public enum StackDirection
{
    /// <summary>The catalog value <c>row</c>.</summary>
    Row,

    /// <summary>The catalog value <c>column</c>.</summary>
    Column,
}

/// <summary>Converts generated enums to the values the wire format uses.</summary>
public static partial class WireValues
{
    /// <summary>The catalog value for a <see cref="StackDirection"/>.</summary>
    public static string ToWire(this StackDirection value) =>
        value switch
        {
            StackDirection.Row => "row",
            StackDirection.Column => "column",
            _ => throw new ArgumentOutOfRangeException(nameof(value)),
        };
}

/// <summary>Values the catalog accepts for this prop.</summary>
public enum Tone
{
    /// <summary>The catalog value <c>neutral</c>.</summary>
    Neutral,

    /// <summary>The catalog value <c>muted</c>.</summary>
    Muted,

    /// <summary>The catalog value <c>info</c>.</summary>
    Info,

    /// <summary>The catalog value <c>success</c>.</summary>
    Success,

    /// <summary>The catalog value <c>warning</c>.</summary>
    Warning,

    /// <summary>The catalog value <c>danger</c>.</summary>
    Danger,
}

/// <summary>Converts generated enums to the values the wire format uses.</summary>
public static partial class WireValues
{
    /// <summary>The catalog value for a <see cref="Tone"/>.</summary>
    public static string ToWire(this Tone value) =>
        value switch
        {
            Tone.Neutral => "neutral",
            Tone.Muted => "muted",
            Tone.Info => "info",
            Tone.Success => "success",
            Tone.Warning => "warning",
            Tone.Danger => "danger",
            _ => throw new ArgumentOutOfRangeException(nameof(value)),
        };
}

/// <summary>Builders for every component in the hub's catalog.</summary>
public static class Ui
{
    /// <summary>Page.</summary>
    public static Node Page(string? title = null) =>
        NodeBuilder.Build(
            "Page",
            new Dictionary<string, object?>
            {
            ["title"] = title,
            });

    /// <summary>Section.</summary>
    public static Node Section(string? title = null, string? description = null, bool? collapsible = null) =>
        NodeBuilder.Build(
            "Section",
            new Dictionary<string, object?>
            {
            ["title"] = title,
            ["description"] = description,
            ["collapsible"] = collapsible,
            });

    /// <summary>Stack.</summary>
    public static Node Stack(StackDirection? direction = null, Gap? gap = null, Align? align = null, bool? wrap = null) =>
        NodeBuilder.Build(
            "Stack",
            new Dictionary<string, object?>
            {
            ["direction"] = direction?.ToWire(),
            ["gap"] = gap?.ToWire(),
            ["align"] = align?.ToWire(),
            ["wrap"] = wrap,
            });

    /// <summary>Grid.</summary>
    public static Node Grid(int columns, Gap? gap = null) =>
        NodeBuilder.Build(
            "Grid",
            new Dictionary<string, object?>
            {
            ["columns"] = columns,
            ["gap"] = gap?.ToWire(),
            });

    /// <summary>Card.</summary>
    public static Node Card(string? title = null, Tone? tone = null) =>
        NodeBuilder.Build(
            "Card",
            new Dictionary<string, object?>
            {
            ["title"] = title,
            ["tone"] = tone?.ToWire(),
            });

    /// <summary>Tabs.</summary>
    public static Node Tabs(IReadOnlyList<IReadOnlyDictionary<string, object?>> tabs, string? activeId = null) =>
        NodeBuilder.Build(
            "Tabs",
            new Dictionary<string, object?>
            {
            ["tabs"] = tabs,
            ["activeId"] = activeId,
            });

    /// <summary>Divider.</summary>
    public static Node Divider(Gap? spacing = null) =>
        NodeBuilder.Build(
            "Divider",
            new Dictionary<string, object?>
            {
            ["spacing"] = spacing?.ToWire(),
            });

    /// <summary>Modal.</summary>
    public static Node Modal(string title, bool? open = null, Size? size = null) =>
        NodeBuilder.Build(
            "Modal",
            new Dictionary<string, object?>
            {
            ["title"] = title,
            ["open"] = open,
            ["size"] = size?.ToWire(),
            });

    /// <summary>Heading.</summary>
    public static Node Heading(string text, HeadingLevel? level = null) =>
        NodeBuilder.Build(
            "Heading",
            new Dictionary<string, object?>
            {
            ["text"] = text,
            ["level"] = level?.ToWire(),
            });

    /// <summary>Text.</summary>
    public static Node Text(string text, Tone? tone = null, Size? size = null, bool? emphasis = null) =>
        NodeBuilder.Build(
            "Text",
            new Dictionary<string, object?>
            {
            ["text"] = text,
            ["tone"] = tone?.ToWire(),
            ["size"] = size?.ToWire(),
            ["emphasis"] = emphasis,
            });

    /// <summary>Badge.</summary>
    public static Node Badge(string label, Tone? tone = null) =>
        NodeBuilder.Build(
            "Badge",
            new Dictionary<string, object?>
            {
            ["label"] = label,
            ["tone"] = tone?.ToWire(),
            });

    /// <summary>StatTile.</summary>
    public static Node StatTile(string label, string value, string? caption = null, Tone? tone = null, IReadOnlyDictionary<string, object?>? source = null) =>
        NodeBuilder.Build(
            "StatTile",
            new Dictionary<string, object?>
            {
            ["label"] = label,
            ["value"] = value,
            ["caption"] = caption,
            ["tone"] = tone?.ToWire(),
            ["source"] = source,
            });

    /// <summary>KeyValueList.</summary>
    public static Node KeyValueList(IReadOnlyList<IReadOnlyDictionary<string, object?>> items, IReadOnlyDictionary<string, object?>? source = null) =>
        NodeBuilder.Build(
            "KeyValueList",
            new Dictionary<string, object?>
            {
            ["items"] = items,
            ["source"] = source,
            });

    /// <summary>Table.</summary>
    public static Node Table(IReadOnlyList<IReadOnlyDictionary<string, object?>> columns, IReadOnlyList<IReadOnlyDictionary<string, object?>>? rows = null, IReadOnlyDictionary<string, object?>? dataSource = null, IReadOnlyDictionary<string, object?>? rowAction = null, string? emptyMessage = null, int? page = null, int? pageSize = null, int? total = null, IReadOnlyDictionary<string, object?>? source = null) =>
        NodeBuilder.Build(
            "Table",
            new Dictionary<string, object?>
            {
            ["columns"] = columns,
            ["rows"] = rows,
            ["dataSource"] = dataSource,
            ["rowAction"] = rowAction,
            ["emptyMessage"] = emptyMessage,
            ["page"] = page,
            ["pageSize"] = pageSize,
            ["total"] = total,
            ["source"] = source,
            });

    /// <summary>Chart.</summary>
    public static Node Chart(ChartKind kind, string xKey, IReadOnlyList<IReadOnlyDictionary<string, object?>> series, IReadOnlyList<IReadOnlyDictionary<string, object?>>? data = null, IReadOnlyDictionary<string, object?>? source = null) =>
        NodeBuilder.Build(
            "Chart",
            new Dictionary<string, object?>
            {
            ["kind"] = kind.ToWire(),
            ["xKey"] = xKey,
            ["series"] = series,
            ["data"] = data,
            ["source"] = source,
            });

    /// <summary>Alert.</summary>
    public static Node Alert(AlertLevel level, string message, string? title = null) =>
        NodeBuilder.Build(
            "Alert",
            new Dictionary<string, object?>
            {
            ["level"] = level.ToWire(),
            ["message"] = message,
            ["title"] = title,
            });

    /// <summary>EmptyState.</summary>
    public static Node EmptyState(string title, string? message = null, IReadOnlyDictionary<string, object?>? action = null, string? actionLabel = null) =>
        NodeBuilder.Build(
            "EmptyState",
            new Dictionary<string, object?>
            {
            ["title"] = title,
            ["message"] = message,
            ["action"] = action,
            ["actionLabel"] = actionLabel,
            });

    /// <summary>Timeline.</summary>
    public static Node Timeline(IReadOnlyList<IReadOnlyDictionary<string, object?>> items) =>
        NodeBuilder.Build(
            "Timeline",
            new Dictionary<string, object?>
            {
            ["items"] = items,
            });

    /// <summary>Form.</summary>
    public static Node Form(string actionId, string? submitLabel = null, IReadOnlyDictionary<string, object?>? confirm = null) =>
        NodeBuilder.Build(
            "Form",
            new Dictionary<string, object?>
            {
            ["actionId"] = actionId,
            ["submitLabel"] = submitLabel,
            ["confirm"] = confirm,
            });

    /// <summary>TextField.</summary>
    public static Node TextField(string name, string label, bool? required = null, string? help = null, bool? disabled = null, IReadOnlyDictionary<string, object?>? visibleWhen = null, string? value = null, string? placeholder = null) =>
        NodeBuilder.Build(
            "TextField",
            new Dictionary<string, object?>
            {
            ["name"] = name,
            ["label"] = label,
            ["required"] = required,
            ["help"] = help,
            ["disabled"] = disabled,
            ["visibleWhen"] = visibleWhen,
            ["value"] = value,
            ["placeholder"] = placeholder,
            });

    /// <summary>TextArea.</summary>
    public static Node TextArea(string name, string label, bool? required = null, string? help = null, bool? disabled = null, IReadOnlyDictionary<string, object?>? visibleWhen = null, string? value = null, int? rows = null) =>
        NodeBuilder.Build(
            "TextArea",
            new Dictionary<string, object?>
            {
            ["name"] = name,
            ["label"] = label,
            ["required"] = required,
            ["help"] = help,
            ["disabled"] = disabled,
            ["visibleWhen"] = visibleWhen,
            ["value"] = value,
            ["rows"] = rows,
            });

    /// <summary>NumberField.</summary>
    public static Node NumberField(string name, string label, bool? required = null, string? help = null, bool? disabled = null, IReadOnlyDictionary<string, object?>? visibleWhen = null, double? value = null, double? min = null, double? max = null, double? step = null) =>
        NodeBuilder.Build(
            "NumberField",
            new Dictionary<string, object?>
            {
            ["name"] = name,
            ["label"] = label,
            ["required"] = required,
            ["help"] = help,
            ["disabled"] = disabled,
            ["visibleWhen"] = visibleWhen,
            ["value"] = value,
            ["min"] = min,
            ["max"] = max,
            ["step"] = step,
            });

    /// <summary>Select.</summary>
    public static Node Select(string name, string label, IReadOnlyList<IReadOnlyDictionary<string, object?>> options, bool? required = null, string? help = null, bool? disabled = null, IReadOnlyDictionary<string, object?>? visibleWhen = null, string? value = null) =>
        NodeBuilder.Build(
            "Select",
            new Dictionary<string, object?>
            {
            ["name"] = name,
            ["label"] = label,
            ["options"] = options,
            ["required"] = required,
            ["help"] = help,
            ["disabled"] = disabled,
            ["visibleWhen"] = visibleWhen,
            ["value"] = value,
            });

    /// <summary>MultiSelect.</summary>
    public static Node MultiSelect(string name, string label, IReadOnlyList<IReadOnlyDictionary<string, object?>> options, bool? required = null, string? help = null, bool? disabled = null, IReadOnlyDictionary<string, object?>? visibleWhen = null, IReadOnlyList<string>? value = null) =>
        NodeBuilder.Build(
            "MultiSelect",
            new Dictionary<string, object?>
            {
            ["name"] = name,
            ["label"] = label,
            ["options"] = options,
            ["required"] = required,
            ["help"] = help,
            ["disabled"] = disabled,
            ["visibleWhen"] = visibleWhen,
            ["value"] = value,
            });

    /// <summary>DateField.</summary>
    public static Node DateField(string name, string label, bool? required = null, string? help = null, bool? disabled = null, IReadOnlyDictionary<string, object?>? visibleWhen = null, string? value = null) =>
        NodeBuilder.Build(
            "DateField",
            new Dictionary<string, object?>
            {
            ["name"] = name,
            ["label"] = label,
            ["required"] = required,
            ["help"] = help,
            ["disabled"] = disabled,
            ["visibleWhen"] = visibleWhen,
            ["value"] = value,
            });

    /// <summary>DateRange.</summary>
    public static Node DateRange(string name, string label, bool? required = null, string? help = null, bool? disabled = null, IReadOnlyDictionary<string, object?>? visibleWhen = null, string? from = null, string? to = null) =>
        NodeBuilder.Build(
            "DateRange",
            new Dictionary<string, object?>
            {
            ["name"] = name,
            ["label"] = label,
            ["required"] = required,
            ["help"] = help,
            ["disabled"] = disabled,
            ["visibleWhen"] = visibleWhen,
            ["from"] = from,
            ["to"] = to,
            });

    /// <summary>Checkbox.</summary>
    public static Node Checkbox(string name, string label, bool? required = null, string? help = null, bool? disabled = null, IReadOnlyDictionary<string, object?>? visibleWhen = null, bool? @checked = null) =>
        NodeBuilder.Build(
            "Checkbox",
            new Dictionary<string, object?>
            {
            ["name"] = name,
            ["label"] = label,
            ["required"] = required,
            ["help"] = help,
            ["disabled"] = disabled,
            ["visibleWhen"] = visibleWhen,
            ["checked"] = @checked,
            });

    /// <summary>Switch.</summary>
    public static Node Switch(string name, string label, bool? required = null, string? help = null, bool? disabled = null, IReadOnlyDictionary<string, object?>? visibleWhen = null, bool? @checked = null) =>
        NodeBuilder.Build(
            "Switch",
            new Dictionary<string, object?>
            {
            ["name"] = name,
            ["label"] = label,
            ["required"] = required,
            ["help"] = help,
            ["disabled"] = disabled,
            ["visibleWhen"] = visibleWhen,
            ["checked"] = @checked,
            });

    /// <summary>RadioGroup.</summary>
    public static Node RadioGroup(string name, string label, IReadOnlyList<IReadOnlyDictionary<string, object?>> options, bool? required = null, string? help = null, bool? disabled = null, IReadOnlyDictionary<string, object?>? visibleWhen = null, string? value = null) =>
        NodeBuilder.Build(
            "RadioGroup",
            new Dictionary<string, object?>
            {
            ["name"] = name,
            ["label"] = label,
            ["options"] = options,
            ["required"] = required,
            ["help"] = help,
            ["disabled"] = disabled,
            ["visibleWhen"] = visibleWhen,
            ["value"] = value,
            });

    /// <summary>FileUpload.</summary>
    public static Node FileUpload(string name, string label, bool? required = null, string? help = null, bool? disabled = null, IReadOnlyDictionary<string, object?>? visibleWhen = null, IReadOnlyList<string>? accept = null, bool? multiple = null) =>
        NodeBuilder.Build(
            "FileUpload",
            new Dictionary<string, object?>
            {
            ["name"] = name,
            ["label"] = label,
            ["required"] = required,
            ["help"] = help,
            ["disabled"] = disabled,
            ["visibleWhen"] = visibleWhen,
            ["accept"] = accept,
            ["multiple"] = multiple,
            });

    /// <summary>Hidden.</summary>
    public static Node Hidden(string name, string value) =>
        NodeBuilder.Build(
            "Hidden",
            new Dictionary<string, object?>
            {
            ["name"] = name,
            ["value"] = value,
            });

    /// <summary>Button.</summary>
    public static Node Button(string label, ButtonVariant? variant = null, Size? size = null, bool? disabled = null, IReadOnlyDictionary<string, object?>? action = null, IReadOnlyDictionary<string, object?>? confirm = null) =>
        NodeBuilder.Build(
            "Button",
            new Dictionary<string, object?>
            {
            ["label"] = label,
            ["variant"] = variant?.ToWire(),
            ["size"] = size?.ToWire(),
            ["disabled"] = disabled,
            ["action"] = action,
            ["confirm"] = confirm,
            });

    /// <summary>Link.</summary>
    public static Node Link(string label, string? screenId = null, string? satelliteId = null, IReadOnlyDictionary<string, string>? @params = null, string? href = null) =>
        NodeBuilder.Build(
            "Link",
            new Dictionary<string, object?>
            {
            ["label"] = label,
            ["screenId"] = screenId,
            ["satelliteId"] = satelliteId,
            ["params"] = @params,
            ["href"] = href,
            });

    /// <summary>MenuButton.</summary>
    public static Node MenuButton(string label, IReadOnlyList<IReadOnlyDictionary<string, object?>> items) =>
        NodeBuilder.Build(
            "MenuButton",
            new Dictionary<string, object?>
            {
            ["label"] = label,
            ["items"] = items,
            });
}
