import { CURRENT_PROTOCOL_VERSION } from "@portal/protocol";

/**
 * Is this process serving? Nothing more.
 *
 * The compose healthcheck used to `curl /`, which was free when the landing
 * page was a list of links. It stopped being free the moment that page started
 * asking every satellite for its manifest, its health and its summary screen:
 * a liveness probe every five seconds became continuous load on the whole
 * estate, and — because the summary read is audited — a steady drip of
 * `screen.read` records generated by a machine and attributed to a person.
 *
 * That last part is the one that matters. The audit log's whole value is
 * answering "which records were read, by whom, when", and an entry written by
 * a healthcheck is noise in exactly the evidence a regulator or a client
 * security review would ask for.
 *
 * So: no registry, no satellites, no principal, no log. Reaching this route at
 * all is the answer, and the body is a courtesy.
 *
 * It deliberately does *not* report on satellites. A hub marked unhealthy
 * because a solution is down would contradict the property the whole design
 * rests on — one satellite failing is one card, not an outage — and compose
 * already gates startup on the satellites' own healthchecks.
 */
export const dynamic = "force-dynamic";

export function GET(): Response {
  return Response.json({ status: "ok", protocol: CURRENT_PROTOCOL_VERSION });
}
